compatibility_date = "2026-05-03"
main = "src/index.ts"
name = "roncalphoto-email-worker"
upload_source_maps = true
workers_dev = false

[[send_email]]
name = "SEND_EMAIL"

[observability]
enabled = true

[vars]
FROM_EMAIL = "replace-with-verified-sender@example.com"
FROM_NAME = "RoncalPhoto"
