/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTagsRouteImport } from './routes/_app.tags'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppPhotosRouteImport } from './routes/_app.photos'
import { Route as AppComponentsRouteImport } from './routes/_app.components'
import { Route as AppTagsSlugRouteImport } from './routes/_app.tags.$slug'
import { Route as AppSessionsNewRouteImport } from './routes/_app.sessions.new'
import { Route as AppSessionsSlugRouteImport } from './routes/_app.sessions.$slug'
import { Route as AppPhotosNewRouteImport } from './routes/_app.photos.new'
import { Route as AppPhotosIdRouteImport } from './routes/_app.photos.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosRoute = AppPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentsRoute = AppComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsSlugRoute = AppTagsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppTagsRoute,
} as any)
const AppSessionsNewRoute = AppSessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSessionsRoute,
} as any)
const AppSessionsSlugRoute = AppSessionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppSessionsRoute,
} as any)
const AppPhotosNewRoute = AppPhotosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPhotosRoute,
} as any)
const AppPhotosIdRoute = AppPhotosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPhotosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/components': typeof AppComponentsRoute
  '/photos': typeof AppPhotosRouteWithChildren
  '/sessions': typeof AppSessionsRouteWithChildren
  '/tags': typeof AppTagsRouteWithChildren
  '/photos/$id': typeof AppPhotosIdRoute
  '/photos/new': typeof AppPhotosNewRoute
  '/sessions/$slug': typeof AppSessionsSlugRoute
  '/sessions/new': typeof AppSessionsNewRoute
  '/tags/$slug': typeof AppTagsSlugRoute
}
export interface FileRoutesByTo {
  '/components': typeof AppComponentsRoute
  '/photos': typeof AppPhotosRouteWithChildren
  '/sessions': typeof AppSessionsRouteWithChildren
  '/tags': typeof AppTagsRouteWithChildren
  '/': typeof AppIndexRoute
  '/photos/$id': typeof AppPhotosIdRoute
  '/photos/new': typeof AppPhotosNewRoute
  '/sessions/$slug': typeof AppSessionsSlugRoute
  '/sessions/new': typeof AppSessionsNewRoute
  '/tags/$slug': typeof AppTagsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/components': typeof AppComponentsRoute
  '/_app/photos': typeof AppPhotosRouteWithChildren
  '/_app/sessions': typeof AppSessionsRouteWithChildren
  '/_app/tags': typeof AppTagsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/photos/$id': typeof AppPhotosIdRoute
  '/_app/photos/new': typeof AppPhotosNewRoute
  '/_app/sessions/$slug': typeof AppSessionsSlugRoute
  '/_app/sessions/new': typeof AppSessionsNewRoute
  '/_app/tags/$slug': typeof AppTagsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/photos'
    | '/sessions'
    | '/tags'
    | '/photos/$id'
    | '/photos/new'
    | '/sessions/$slug'
    | '/sessions/new'
    | '/tags/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/components'
    | '/photos'
    | '/sessions'
    | '/tags'
    | '/'
    | '/photos/$id'
    | '/photos/new'
    | '/sessions/$slug'
    | '/sessions/new'
    | '/tags/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/components'
    | '/_app/photos'
    | '/_app/sessions'
    | '/_app/tags'
    | '/_app/'
    | '/_app/photos/$id'
    | '/_app/photos/new'
    | '/_app/sessions/$slug'
    | '/_app/sessions/new'
    | '/_app/tags/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos': {
      id: '/_app/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AppPhotosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/components': {
      id: '/_app/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof AppComponentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags/$slug': {
      id: '/_app/tags/$slug'
      path: '/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof AppTagsSlugRouteImport
      parentRoute: typeof AppTagsRoute
    }
    '/_app/sessions/new': {
      id: '/_app/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/sessions/$slug': {
      id: '/_app/sessions/$slug'
      path: '/$slug'
      fullPath: '/sessions/$slug'
      preLoaderRoute: typeof AppSessionsSlugRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/photos/new': {
      id: '/_app/photos/new'
      path: '/new'
      fullPath: '/photos/new'
      preLoaderRoute: typeof AppPhotosNewRouteImport
      parentRoute: typeof AppPhotosRoute
    }
    '/_app/photos/$id': {
      id: '/_app/photos/$id'
      path: '/$id'
      fullPath: '/photos/$id'
      preLoaderRoute: typeof AppPhotosIdRouteImport
      parentRoute: typeof AppPhotosRoute
    }
  }
}

interface AppPhotosRouteChildren {
  AppPhotosIdRoute: typeof AppPhotosIdRoute
  AppPhotosNewRoute: typeof AppPhotosNewRoute
}

const AppPhotosRouteChildren: AppPhotosRouteChildren = {
  AppPhotosIdRoute: AppPhotosIdRoute,
  AppPhotosNewRoute: AppPhotosNewRoute,
}

const AppPhotosRouteWithChildren = AppPhotosRoute._addFileChildren(
  AppPhotosRouteChildren,
)

interface AppSessionsRouteChildren {
  AppSessionsSlugRoute: typeof AppSessionsSlugRoute
  AppSessionsNewRoute: typeof AppSessionsNewRoute
}

const AppSessionsRouteChildren: AppSessionsRouteChildren = {
  AppSessionsSlugRoute: AppSessionsSlugRoute,
  AppSessionsNewRoute: AppSessionsNewRoute,
}

const AppSessionsRouteWithChildren = AppSessionsRoute._addFileChildren(
  AppSessionsRouteChildren,
)

interface AppTagsRouteChildren {
  AppTagsSlugRoute: typeof AppTagsSlugRoute
}

const AppTagsRouteChildren: AppTagsRouteChildren = {
  AppTagsSlugRoute: AppTagsSlugRoute,
}

const AppTagsRouteWithChildren =
  AppTagsRoute._addFileChildren(AppTagsRouteChildren)

interface AppRouteChildren {
  AppComponentsRoute: typeof AppComponentsRoute
  AppPhotosRoute: typeof AppPhotosRouteWithChildren
  AppSessionsRoute: typeof AppSessionsRouteWithChildren
  AppTagsRoute: typeof AppTagsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComponentsRoute: AppComponentsRoute,
  AppPhotosRoute: AppPhotosRouteWithChildren,
  AppSessionsRoute: AppSessionsRouteWithChildren,
  AppTagsRoute: AppTagsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
