name = "roncalphoto-api"
main = "src/index.ts"
compatibility_date = "2026-05-03"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[[d1_databases]]
binding = "DB_RONCALPHOTO"
database_id = "da274846-1de9-4c1a-92fd-0e56c5f0f7b5"
database_name = "roncalphoto"
migrations_dir = "src/db/migrations"

[[services]]
binding = "EMAIL_WORKER"
service = "roncalphoto-email-worker"

[observability]
enabled = true

[vars]
ALLOWED_ORIGINS = "https://admin.estudioroncal.com,https://estudioroncal.com"
LOG_LEVEL = "info"
NODE_ENV = "production"
BETTER_AUTH_URL = "https://api.murga.ing"
PHOTOS_ADMIN_URL = "https://admin.estudioroncal.com"
